### ISSUE TITLE
Add "helper text" option to Field

### ISSUE THREAD

**Issue by averyvery** [vigetlabs/colonel-kurtz#101]
Sometimes a field needs more than a label. That's where helper text — text that appears at the bottom of Field — would be helpful.

**Comment by nhunzaker** [comment]
How does this feel?

<img width="789" alt="screen shot 2015-08-28 at 8 39 02 am" src="https://cloud.githubusercontent.com/assets/590904/9546385/4076ffd2-4d60-11e5-9954-412f944efc44.png">

**Comment by averyvery** [comment]
Great! On NTHP I added one just like this but italicized it, which I liked a little more, but that's just me.

**Comment by nhunzaker** [comment]
Just following Material Design here, feel free to override it down stream on NTHP :)

**Comment by averyvery** [comment]
gotcha

**Comment by nhunzaker** [comment]
:+1:. This'll hit with v2.22.0
