### ISSUE TITLE
Long field labels collide with control

### ISSUE THREAD

**Issue by averyvery** [vigetlabs/colonel-kurtz#102]
Screenshot: 

![screen shot 2015-08-26 at 4 13 34 pm](https://cloud.githubusercontent.com/assets/72114/9507741/72be5098-4c0d-11e5-9de0-435b3e9f51ff.png)

**Comment by nhunzaker** [comment]
Awesome. I'll add some padding to the right hand side of that label when #103 hits.

**Comment by nhunzaker** [comment]
![screen shot 2015-08-31 at 12 57 20 pm](https://cloud.githubusercontent.com/assets/590904/9584570/d5c08320-4fdf-11e5-9cfc-6a1542f5b5e8.png)

Feelin good?

**Comment by averyvery** [comment]
yep, thanks!
