### ISSUE TITLE
UI considerations for drag and drop restrictions

### ISSUE THREAD

**Issue by ltk** [vigetlabs/colonel-kurtz#112]
CK imposes rules around what block types and how many blocks you can gave as children of a given block. How do we reflect these constraints within the drag and drop interface?

In the demo below, the dark grey section is full, so the item can't be moved within. Should we try to surface a message that says why the block can't be dropped in a particular location?
![demo](https://s3.amazonaws.com/vigesharing-is-vigecaring/lkurtz/ck-dragon-demo-full-section.gif)

**Comment by mackermedia** [comment]
Would it be crazy to show all available drop zones and ones that aren't
droppable have them have hatch marks or some other indicator?

**Comment by nhunzaker** [comment]
Ah... this was one of the major reasons we dropped drag and drop in 2.0 (in addition to some other UX issues). I like the idea of showing a message

**Comment by ltk** [comment]
okay, a good combo might to show disallowed drop zones with a different border color/style, and insert a message about the reason for disallowal into the middle of the zone. I'll work this.

**Comment by ltk** [comment]
![in progress](https://s3.amazonaws.com/vigesharing-is-vigecaring/lkurtz/ck-dragon-demo-drag-errors.gif)

**Comment by cwmanning** [comment]
What about `cursor: no-drop;` on disallowed areas? I think it's already used on areas when you've reached the max number of allowed children.

**Comment by nhunzaker** [comment]
Going to close this out, but let's pick it back up if we ever get into drag and drop again.
