### ISSUE TITLE
uid depended on by this package is broken and no longer maintained

### ISSUE THREAD

**Issue by chitezh** [vigetlabs/colonel-kurtz#131]
Please, upgrade to `uuid` or any other unique id generator

The issue has existed for so long see
https://github.com/matthewmueller/uid/pull/9 and https://github.com/matthewmueller/uid/pull/5

**Comment by nhunzaker** [comment]
Hey @chitezh! We've reached out to the maintainer of uid (https://github.com/matthewmueller/uid/pull/9#issuecomment-342194865). In the meantime, we only use this module to generate unique names to match up labels and inputs. I've inlined it in https://github.com/vigetlabs/colonel-kurtz/pull/133.

Thanks for calling our attention to it!

**Comment by nhunzaker** [comment]
I will prepare a release later today. I want to circle up on some PropTypes warnings before we send out another release.

**Comment by nhunzaker** [comment]
Colonel Kurtz no longer depends on `uid`. We'll continue to follow up with the maintainer of `uid`.

This has been released in version 4.3.0

**Comment by chitezh** [comment]
Awesome! Thanks for the speedy response
