### ISSUE TITLE
Table/Row View: Clicking a row should select the corresponding item

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/colonel-kurtz#142]
Right now we're only allowing clicks on/around the radio button within a row. It would be nice to allow users to click anywhere in the row to select an item. This might be tricky considering tags are clickable within a row and we can't nest buttons or anchors.

Let me know if I should elaborate.

**Comment by nhunzaker** [comment]
Could you provide a screenshot of this view? Is this possible a ticket for ArsArsenal?

**Comment by solomonhawk** [comment]
You're too kind Nate. This should be on ArsArsenal. I'll get a screenshot in there, too. Whoops, sorry for the confusion.
