### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [vigetlabs/colonel-kurtz#190]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by cwmanning** [comment]
@codehangen this project is not under active development. We will continue to support it as necessary for our current project use. I imagine that will mostly involve small bug fixes and security patches. Does that help? Let me know if you have any related questions.

**Comment by ghost** [comment]
Hi cwmanning.

> @codehangen this project is not under active development. 

Thanks for feedback.

> We will continue to support it as necessary for our current project use. 

So, I would like to help this open source project.

> I imagine that will mostly involve small bug fixes and security patches. 

Exactly, I would like to help with bug-fixes and security-patches if possible and if this repository has the possibility to accept my contributions.

> Does that help? Let me know if you have any related questions.

- My question in general was whether the repository was active so I could contribute. 
- As you answered my question I'm going to close this issue, and try to help with some security-patches or bug-fixes.

*Have a great day, and thank you for your patience in answering my questions.*
