### ISSUE TITLE
Remove preview mode in favor of live preview

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/colonel-kurtz#38]
The `preview` functionality has never seen the light of day. We are currently discussing replacing it with a live preview mode that would require some server integration. Essentially:

- Every change would post to a live preview endpoint, the result would be targeted to an iFrame.
- This iframe would be resizable similarly to the responsive web design tool in Firefox
- Instead of tabs, we'd have a switch (possibly the material design one) that would toggle this functionality.

**Comment by nhunzaker** [comment]
cc @ltk @hellokv

**Comment by ltk** [comment]
I think this should be a part of the main application (like the WCS app). CK should just provide an event that the main application can use to grab the json from the editor and post to whatever particular endpoint. Thats my 2 cents.

**Comment by nhunzaker** [comment]
@ltk It sounds like our first step, regardless, is to remove Preview and the Tabs.
