### ISSUE TITLE
Add background image block type

### ISSUE THREAD

**Issue by dmacgregor** [vigetlabs/colonel-kurtz#43]
Create a background image block type, an admin can upload an image and that image would then become the background for any blocks nested within that background image block.

This is related to the nested block ticket.

**Comment by mattgi** [comment]
+1

**Comment by nhunzaker** [comment]
Just to close this one out, we sort of have this. As of `~2.14.0` we have a menu API and dialog component. You can use these to create a settings menu, [as seen in the example](https://github.com/vigetlabs/colonel-kurtz/blob/master/example/blockTypes/Section.jsx), or you could just make an input in your particular block component to set a field in the block content object.
