### ISSUE TITLE
Dialogs should expand to fill the screen on smaller viewports. Handle scrolling

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/colonel-kurtz#63]
What if dialogs took up the entire screen on smaller devices? Additionally, it would be nice for dialogs to handle scrolling.

**Comment by nhunzaker** [comment]
@cwmanning closeable?

**Comment by cwmanning** [comment]
"Dialogs should expand to fill the screen" seems to be largely in-place already. Closing.
