### ISSUE TITLE
Colonel Kurtz 2.16.0

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/colonel-kurtz#72]
- [x] #63 
- [x] Add entry to changelog about dialogs @cwmanning 
- [x] Add @cwmanning as contributor :smiley_cat: 
- [x] Confirm changes in release candidate @cwmanning @nhunzaker
- [x] Update package.json @nhunzaker
- [x] Tag release @nhunzaker
- [x] Deploy @nhunzaker

**Comment by cwmanning** [comment]
RC1 checks out for me.

**Comment by nhunzaker** [comment]
Awesome. I'll send out a release.

**Comment by nhunzaker** [comment]
Done! Excellent work, @cwmanning!
