### ISSUE TITLE
Cursor jumps to end of text inputs

### ISSUE THREAD

**Issue by cwmanning** [vigetlabs/colonel-kurtz#96]
Steps to reproduce:

1. Add a `Field` component or other text input.
2. Type a letter or word into the text input.
3. Move cursor to the beginning of the input via mouse click or `ctrl + a`, begin typing new characters.
4. Notice that the cursor jumps immediately to the end of the input.

Possibly related:
* https://github.com/facebook/react/issues/955
* http://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously

**Comment by solomonhawk** [comment]
Controlled vs uncontrolled input issue, perhaps?

**Comment by nhunzaker** [comment]
@solomonhawk Absolutely.

**Comment by nhunzaker** [comment]
@solomonhawk Wait. You deleted the comment?!

**Comment by nhunzaker** [comment]
Now I'm just talkin to myself, as usual

**Comment by solomonhawk** [comment]
Haha, I assumed my comment wasn't actually helpful given the links Chris posted. Sorry!

**Comment by nhunzaker** [comment]
Fixed.

**Comment by Urvashi98** [comment]
@nhunzaker How did it fixed? May you share some insights?

**Comment by nhunzaker** [comment]
@Urvashi98 a handful of improvements to React DOM resolved this issue, however this can generally show up when using controlled inputs where assigning `value` to an input can cause selection to reset.
